name: Docker Compose CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: fongpakorn
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and tag Docker images
        run: |
          docker compose -f docker-compose.yml build

      - name: Tag and push Backend images
        run: |
          docker tag todo101-todo-backend fongpakorn/todo-backend:latest
          docker push fongpakorn/todo101-todo-backend:latest
      
      - name: Tag and push Frontend image
        run: |
          docker tag todo101-todo-frontend fongpakorn/todo-frontend:latest
          docker push fongpakorn/todo101-todo-frontend:latest